services:
  - type: web
    name: sr-logistics-fleet-management
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sr-logistics-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 5000
    healthCheckPath: /

databases:
  - name: sr-logistics-db
    databaseName: sr_logistics
    user: sr_logistics_user
    plan: free
    region: oregon
